package main

import (
	_ "embed"
	"fmt"
	"strings"
)

var (
	//go:embed ansi/sabacc.ans
	SabaccLogo string
	//go:embed ansi/logBorder.ans
	LogBorder string
)
const (
	Esc = "\u001B["
	Osc = "\u001B]"
	Bel = "\u0007"
)

// ScreenLayout manages the persistent UI layout for the Sabacc game
type ScreenLayout struct {
	// Terminal dimensions
	TerminalW int
	TerminalH int

	// Fixed screen positions for 4 AI players + human player layout
	// AI Player positions (corners of screen)
	AIPlayer1X int // Top-left AI player (Phoo_ja)
	AIPlayer1Y int
	AIPlayer2X int // Top-right AI player (Rsh-Taac)
	AIPlayer2Y int
	AIPlayer3X int // Bottom-left AI player (Soladi)
	AIPlayer3Y int
	AIPlayer4X int // Bottom-right AI player (Ky'Ola)
	AIPlayer4Y int

	// Central game log area
	GameLogX int // Center area for scrolling messages - X pos
	GameLogY int // Center area for scrolling messages - Y pos
	GameLogW int // Width of game log area
	GameLogH int // Height of game log area

	// Human player area (bottom center)
	HumanPlayerX int // Player cards area
	HumanPlayerY int
	HumanNameY   int // Player name/info line

	// Turn indicator area
	TurnIndicatorX int
	TurnIndicatorY int

	// Pot info area  
	PotInfoX int
	PotInfoY int

	// Status bar area (Round/Deck display)
	StatusBarX int
	StatusBarY int

	// Bottom status and menu
	StatusY int // Bottom status line (pots, credits)
	MenuY   int // Action buttons line

	// Card display settings
	CardWidth   int // Width of each card display
	CardHeight  int // Height of each card display
	MaxCardsRow int // Maximum cards per row

	// Face art dimensions
	FaceWidth  int // Width of character face art
	FaceHeight int // Height of character face art

	// Portrait system
	PortraitManager *PortraitManager // Manages external ANSI portrait art

	// Game log system
	GameLog *GameLog

}

// GameLog manages the scrolling message area
type GameLog struct {
	Messages []string // Circular buffer of messages
	MaxLines int      // Maximum lines to display
	StartY   int      // Starting Y position for display
	Width    int      // Width of log area
}

// MenuOption represents a menu choice
type MenuOption struct {
	Key         rune
	Description string
	Enabled     bool
}


// NewScreenLayout creates a new screen layout for fixed 79x24 dimensions
func NewScreenLayout(termW, termH int) *ScreenLayout {
	// Force fixed dimensions regardless of actual terminal size
	fixedW := 79
	fixedH := 24

	layout := &ScreenLayout{
		TerminalW: fixedW,
		TerminalH: fixedH,

		// AI Player positions (4 corners) - adjusted for 9-column portraits
		AIPlayer1X: 1, // Top-left (PHOOJA)
		AIPlayer1Y: 2,
		AIPlayer2X: 71, // Top-right (ASH-TAAC) 
		AIPlayer2Y: 2,
		AIPlayer3X: 1, // Bottom-left (OOLANGA)
		AIPlayer3Y: 9,
		AIPlayer4X: 71, // Bottom-right (KY'ALA) - 9 chars + padding
		AIPlayer4Y: 9,

		// Central game log area (blue bordered box from reference)
		GameLogX: 28,
		GameLogY: 5,
		GameLogW: 25, // Fixed width to match reference file
		GameLogH: 7,  

		// Human player area (bottom center - fixed for 79x24)
		HumanPlayerX: fixedW/2 - 15,
		HumanPlayerY: 17, // Move higher to give space for cards above menu
		HumanNameY:   15,

		// Turn indicator (below game log)
		TurnIndicatorX: 4,
		TurnIndicatorY: 19,

		// Pot info area 
		PotInfoX: 2,
		PotInfoY: 18,

		// Status bar area (left side - Round/Deck display)
		StatusBarX: 2,
		StatusBarY: 21,

		// Status and Menu UI elements
		StatusY: 13, 
		MenuY:   24, // Menu on bottom row for compact display

		// Card and face display settings
		CardWidth:   6,                 // card width (matches card database)
		CardHeight:  5,                 // card height 
		MaxCardsRow: 8,                 // card row limit 
		FaceWidth:   portraitWidth + 2, // Portrait width + 2 for borders (9+2=11)
		FaceHeight:  portraitHeight,    // Portrait height (6 rows)
	}

	// Initialize game log with proper dimensions
	layout.GameLog = &GameLog{
		Messages: make([]string, 0),
		MaxLines: layout.GameLogH+2, 
		StartY:   layout.GameLogY + 2, // Inside border
		Width:    layout.GameLogW+4, // Inside border with padding
	}

	// Initialize portrait manager for external ANSI art
	layout.PortraitManager = NewPortraitManager()



	return layout
}

// InitializeScreen draws the static UI elements once
func (sl *ScreenLayout) InitializeScreen() {
	ClearScreen()

	PrintAnsiLoc(SabaccLogo, 29, 2)
	PrintAnsiLoc(LogBorder, sl.GameLogX-1, sl.GameLogY-1)

	// Draw the 4 AI player areas with face art
	sl.drawAIPlayerAreas()

	// Draw central game log with blue border
	sl.drawGameLogBorder()

	// Initialize game log
	sl.GameLog.Clear()
}

// Helper: Complete CP437 character set (IBM PC character set)
// Code generated by CP437 character set library. DO NOT EDIT.
// These variables represent the complete CP437 character set for ANSI terminal support.
// They are kept as a reference library even if not all are currently used in the application.

var (
	// Control characters (0x00-0x1F)
	
	cp437NUL = "\x00" // Null
	cp437SOH = "\x01" // Start of Header
	cp437STX = "\x02" // Start of Text
	cp437ETX = "\x03" // End of Text
	cp437EOT = "\x04" // End of Transmission
	cp437ENQ = "\x05" // Enquiry
	cp437ACK = "\x06" // Acknowledge
	cp437BEL = "\x07" // Bell
	cp437BS  = "\x08" // Backspace
	cp437HT  = "\x09" // Horizontal Tab
	cp437LF1 = "\x0a" // Line Feed
	cp437VT  = "\x0b" // Vertical Tab
	cp437FF  = "\x0c" // Form Feed
	cp437CR  = "\x0d" // Carriage Return
	cp437SO  = "\x0e" // Shift Out
	cp437SI  = "\x0f" // Shift In
	
	cp437DEL = "\x7f" // Delete

	// Extended characters (0x80-0xFF) - CP437 specific
	cp437C128 = "\x80" // Ç (C with cedilla)
	cp437C129 = "\x81" // ü (u with umlaut)
	cp437C130 = "\x82" // é (e with acute)
	cp437C131 = "\x83" // â (a with circumflex)
	cp437C132 = "\x84" // ä (a with umlaut)
	cp437C133 = "\x85" // à (a with grave)
	cp437C134 = "\x86" // å (a with ring)
	cp437C135 = "\x87" // ç (c with cedilla)
	cp437C136 = "\x88" // ê (e with circumflex)
	cp437C137 = "\x89" // ë (e with umlaut)
	cp437C138 = "\x8a" // è (e with grave)
	cp437C139 = "\x8b" // ï (i with umlaut)
	cp437C140 = "\x8c" // î (i with circumflex)
	cp437C141 = "\x8d" // ì (i with grave)
	cp437C142 = "\x8e" // Ä (A with umlaut)
	cp437C143 = "\x8f" // Å (A with ring)
	cp437C144 = "\x90" // É (E with acute)
	cp437C145 = "\x91" // æ (ae ligature)
	cp437C146 = "\x92" // Æ (AE ligature)
	cp437C147 = "\x93" // ô (o with circumflex)
	cp437C148 = "\x94" // ö (o with umlaut)
	cp437C149 = "\x95" // ò (o with grave)
	cp437C150 = "\x96" // û (u with circumflex)
	cp437C151 = "\x97" // ù (u with grave)
	cp437C152 = "\x98" // ÿ (y with umlaut)
	cp437C153 = "\x99" // Ö (O with umlaut)
	cp437C154 = "\x9a" // Ü (U with umlaut)
	cp437C155 = "\x9b" // ¢ (cent sign)
	cp437C156 = "\x9c" // £ (pound sign)
	cp437C157 = "\x9d" // ¥ (yen sign)
	cp437C158 = "\x9e" // ₧ (peseta sign)
	cp437C159 = "\x9f" // ƒ (function sign)
	cp437C160 = "\xa0" // á (a with acute)
	cp437C161 = "\xa1" // í (i with acute)
	cp437C162 = "\xa2" // ó (o with acute)
	cp437C163 = "\xa3" // ú (u with acute)
	cp437C164 = "\xa4" // ñ (n with tilde)
	cp437C165 = "\xa5" // Ñ (N with tilde)
	cp437C166 = "\xa6" // ª (feminine ordinal)
	cp437C167 = "\xa7" // º (masculine ordinal)
	cp437C168 = "\xa8" // ¿ (inverted question mark)
	cp437C169 = "\xa9" // ⌐ (reversed not sign)
	cp437C170 = "\xaa" // ¬ (not sign)
	cp437C171 = "\xab" // ½ (one half)
	cp437C172 = "\xac" // ¼ (one quarter)
	cp437C173 = "\xad" // ¡ (inverted exclamation mark)
	cp437C174 = "\xae" // « (left double angle quote)
	cp437C175 = "\xaf" // » (right double angle quote)
	cp437C176 = "\xb0" // ░ (light shade)
	cp437C177 = "\xb1" // ▒ (medium shade)
	cp437C178 = "\xb2" // ▓ (dark shade)
	cp437C179 = "\xb3" // │ (vertical line)
	cp437C180 = "\xb4" // ┤ (right T)
	cp437C181 = "\xb5" // ╡ (right double T)
	cp437C182 = "\xb6" // ╢ (double vertical)
	cp437C183 = "\xb7" // ╖ (double top-right)
	cp437C184 = "\xb8" // ╕ (double bottom-right)
	cp437C185 = "\xb9" // ╣ (double right T)
	cp437C186 = "\xba" // ║ (double vertical)
	cp437C187 = "\xbb" // ╗ (double top-right)
	cp437C188 = "\xbc" // ╝ (double bottom-right)
	cp437C189 = "\xbd" // ╜ (double bottom-left)
	cp437C190 = "\xbe" // ╛ (double top-left)
	cp437C191 = "\xbf" // ┐ (top-right corner)
	cp437C192 = "\xc0" // └ (bottom-left corner)
	cp437C193 = "\xc1" // ┴ (bottom T)
	cp437C194 = "\xc2" // ┬ (top T)
	cp437C195 = "\xc3" // ├ (left T)
	cp437C196 = "\xc4" // ─ (horizontal line)
	cp437C197 = "\xc5" // ┼ (cross)
	cp437C198 = "\xc6" // ╞ (left double T)
	cp437C199 = "\xc7" // ╟ (double left T)
	cp437C200 = "\xc8" // ╚ (double bottom-left)
	cp437C201 = "\xc9" // ╔ (double top-left)
	cp437C202 = "\xca" // ╩ (double bottom T)
	cp437C203 = "\xcb" // ╦ (double top T)
	cp437C204 = "\xcc" // ╠ (double left T)
	cp437C205 = "\xcd" // ═ (double horizontal)
	cp437C206 = "\xce" // ╬ (double cross)
	cp437C207 = "\xcf" // ╧ (double bottom T)
	cp437C208 = "\xd0" // ╨ (double top T)
	cp437C209 = "\xd1" // ╤ (double top T)
	cp437C210 = "\xd2" // ╥ (double top T)
	cp437C211 = "\xd3" // ╙ (double bottom-left)
	cp437C212 = "\xd4" // ╘ (double bottom-right)
	cp437C213 = "\xd5" // ╒ (double top-left)
	cp437C214 = "\xd6" // ╓ (double top-left)
	cp437C215 = "\xd7" // ╫ (double vertical)
	cp437C216 = "\xd8" // ╪ (double vertical)
	cp437C217 = "\xd9" // ┘ (bottom-right corner)
	cp437C218 = "\xda" // ┌ (top-left corner)
	cp437C219 = "\xdb" // █ (solid block)
	cp437C220 = "\xdc" // ▄ (bottom half block)
	cp437C221 = "\xdd" // ▌ (left half block)
	cp437C222 = "\xde" // ▐ (right half block)
	cp437C223 = "\xdf" // ▀ (top half block)
	cp437C224 = "\xe0" // α (alpha)
	cp437C225 = "\xe1" // ß (beta)
	cp437C226 = "\xe2" // Γ (gamma)
	cp437C227 = "\xe3" // π (pi)
	cp437C228 = "\xe4" // Σ (sigma)
	cp437C229 = "\xe5" // σ (sigma)
	cp437C230 = "\xe6" // µ (mu)
	cp437C231 = "\xe7" // τ (tau)
	cp437C232 = "\xe8" // Φ (phi)
	cp437C233 = "\xe9" // Θ (theta)
	cp437C234 = "\xea" // Ω (omega)
	cp437C235 = "\xeb" // δ (delta)
	cp437C236 = "\xec" // ∞ (infinity)
	cp437C237 = "\xed" // φ (phi)
	cp437C238 = "\xee" // ε (epsilon)
	cp437C239 = "\xef" // ∩ (intersection)
	cp437C240 = "\xf0" // ≡ (equivalence)
	cp437C241 = "\xf1" // ± (plus-minus)
	cp437C242 = "\xf2" // ≥ (greater than or equal)
	cp437C243 = "\xf3" // ≤ (less than or equal)
	cp437C244 = "\xf4" // ⌠ (top half integral)
	cp437C245 = "\xf5" // ⌡ (bottom half integral)
	cp437C246 = "\xf6" // ÷ (division sign)
	cp437C247 = "\xf7" // ≈ (approximately equal)
	cp437C248 = "\xf8" // ° (degree)
	cp437C249 = "\xf9" // ∙ (bullet)
	cp437C250 = "\xfa" // · (middle dot)
	cp437C251 = "\xfb" // √ (square root)
	cp437C252 = "\xfc" // ⁿ (superscript n)
	cp437C253 = "\xfd" // ² (superscript 2)
	cp437C254 = "\xfe" // ■ (black square)
	cp437C255 = "\xff" // (no break space)

	// Box drawing characters
	cp437HOR  = "\xc4" // ─ (horizontal line)
	cp437VER1 = "\xb3" // │ (vertical line)
	cp437TL   = "\xda" // ┌ (top-left corner)
	cp437TR   = "\xbf" // ┐ (top-right corner)
	cp437BL   = "\xc0" // └ (bottom-left corner)
	cp437BR   = "\xd9" // ┘ (bottom-right corner)
	cp437LTJ  = "\xc3" // ├ (left T)
	cp437RTJ  = "\xb4" // ┤ (right T)
	cp437DHOR = "\xcd" // ═ (double horizontal)
	cp437DTL  = "\xc9" // ╔ (double top-left)
	cp437DTR  = "\xbb" // ╗ (double top-right)
	cp437DBL  = "\xc8" // ╚ (double bottom-left)
	cp437DBR  = "\xbc" // ╝ (double bottom-right)
	cp437DVER = "\xba" // ║ (double vertical)
	cp437CRS  = "\xc5" // ┼ (cross)
	cp437DRTJ = "\xb5" // ╡ (right double T)
	cp437DLTJ = "\xc6" // ╞ (left double T)
	cp437DTJ  = "\xcb" // ╦ (double top T)
	cp437DBJ  = "\xca" // ╩ (double bottom T)

	// Block characters
	cp437LIG  = "\xb0" // ░ (light shade)
	cp437MIG  = "\xb1" // ▒ (medium shade)
	cp437DIG  = "\xb2" // ▓ (dark shade)
	cp437FUL  = "\xdb" // █ (solid block)
	cp437BHB  = "\xdc" // ▄ (bottom half block)
	cp437LHB  = "\xdd" // ▌ (left half block)
	cp437RHB  = "\xde" // ▐ (right half block)
	cp437THB  = "\xdf" // ▀ (top half block)

	// Greek and mathematical symbols
	cp437ALP  = "\xe0" // α (alpha)
	cp437BET  = "\xe1" // ß (beta)
	cp437GAM  = "\xe2" // Γ (gamma)
	cp437PI   = "\xe3" // π (pi)
	cp437SIG  = "\xe4" // Σ (sigma)
	cp437SIGL = "\xe5" // σ (sigma)
	cp437MU   = "\xe6" // µ (mu)
	cp437TAU  = "\xe7" // τ (tau)
	cp437PHI  = "\xe8" // Φ (phi)
	cp437THE  = "\xe9" // Θ (theta)
	cp437OM   = "\xea" // Ω (omega)
	cp437DELG = "\xeb" // δ (delta)
	cp437PHIL = "\xed" // φ (phi)
	cp437EPS  = "\xee" // ε (epsilon)
	cp437CAP  = "\xef" // ∩ (intersection)
	cp437EQUV = "\xf0" // ≡ (equivalence)
	cp437PM   = "\xf1" // ± (plus-minus)
	cp437GEQ  = "\xf2" // ≥ (greater than or equal)
	cp437LEQ  = "\xf3" // ≤ (less than or equal)
	cp437INTT = "\xf4" // ⌠ (top half integral)
	cp437INTB = "\xf5" // ⌡ (bottom half integral)
	cp437DIV  = "\xf6" // ÷ (division sign)
	cp437APRX = "\xf7" // ≈ (approximately equal)
	cp437DEG  = "\xf8" // ° (degree)
	cp437BUL  = "\xf9" // ∙ (bullet)
	cp437MID  = "\xfa" // · (middle dot)
	cp437SQRT = "\xfb" // √ (square root)
	cp437SUPN = "\xfc" // ⁿ (superscript n)
	cp437SUP2 = "\xfd" // ² (superscript 2)
	cp437SQU  = "\xfe" // ■ (black square)

	// Descriptive shortcuts - grouped by function
	// Box drawing shortcuts
	
	HORIZONTAL_LINE            = cp437HOR   // ─ (horizontal line)
	VERTICAL_LINE              = cp437VER1  // │ (vertical line)
	TOP_LEFT_CORNER            = cp437TL    // ┌ (top-left corner)
	TOP_RIGHT_CORNER           = cp437TR    // ┐ (top-right corner)
	BOTTOM_LEFT_CORNER         = cp437BL    // └ (bottom-left corner)
	BOTTOM_RIGHT_CORNER        = cp437BR    // ┘ (bottom-right corner)
	LEFT_T_JUNCTION            = cp437LTJ   // ├ (left T)
	RIGHT_T_JUNCTION           = cp437RTJ   // ┤ (right T)
	DOUBLE_HORIZONTAL_LINE     = cp437DHOR  // ═ (double horizontal)
	DOUBLE_TOP_LEFT_CORNER     = cp437DTL   // ╔ (double top-left)
	DOUBLE_TOP_RIGHT_CORNER    = cp437DTR   // ╗ (double top-right)
	DOUBLE_BOTTOM_LEFT_CORNER  = cp437DBL   // ╚ (double bottom-left)
	DOUBLE_BOTTOM_RIGHT_CORNER = cp437DBR   // ╝ (double bottom-right)
	DOUBLE_VERTICAL_LINE       = cp437DVER  // ║ (double vertical)

	// Block shortcuts
	
	SOLID_BLOCK                = cp437FUL   // █ (solid block)
	LIGHT_SHADE                = cp437LIG   // ░ (light shade)
	MEDIUM_SHADE               = cp437MIG   // ▒ (medium shade)
	DARK_SHADE                 = cp437DIG   // ▓ (dark shade)
)

// drawAIPlayerAreas draws the 4 AI player areas with face art
func (sl *ScreenLayout) drawAIPlayerAreas() {
	// AI player names and their positions - must match main.go names
	aiPlayers := []struct {
		name   string
		x, y   int
		isLeft bool
	}{
		{"PHOOJA", sl.AIPlayer1X, sl.AIPlayer1Y, true},     // Top-left
		{"ASH-TAAC", sl.AIPlayer2X, sl.AIPlayer2Y, false}, // Top-right
		{"OOLANGA", sl.AIPlayer3X, sl.AIPlayer3Y, true},    // Bottom-left
		{"KY'ALA", sl.AIPlayer4X, sl.AIPlayer4Y, false},     // Bottom-right
	}

	for i, player := range aiPlayers {
		// Draw portrait from ANSI file
		sl.drawSimpleFaceArt(player.x, player.y, i)

		// Draw player name and credits  
		if player.isLeft {
			MoveCursor(player.x+portraitWidth+1, player.y)
		} else {
			// Right side players: use same fixed 16-column positioning as UpdatePlayerInfo
			MoveCursor(player.x-16, player.y)
		}
		fmt.Printf("%s%s%s", CyanHi, player.name, Reset)
	}
}


// drawSimpleFaceArt draws character faces using external portraits
func (sl *ScreenLayout) drawSimpleFaceArt(x, y, playerIndex int) {
	// Use external portrait from ANSI file
	if sl.PortraitManager != nil {
		sl.PortraitManager.RenderPortrait(x, y, playerIndex)
	}
}

// drawGameLogBorder fills the entire game log area with blue background (no borders)
func (sl *ScreenLayout) drawGameLogBorder() {
	// Use exact positioning from reference file
	logX := sl.GameLogX
	logY := sl.GameLogY
	logW := sl.GameLogW

	// Fill entire game log area with blue background
	for i := 0; i < sl.GameLogH; i++ {
		MoveCursor(logX, logY+i)
		fmt.Printf("\x1b[30;44m%s\x1b[0m", strings.Repeat(" ", logW))
	}
}

// UpdateHeader updates the turn indicator and game status
func (sl *ScreenLayout) UpdateHeader(round, handPot, sabaccPot, deckSize int, currentPlayer string) {
	// Update turn indicator
	sl.drawTurnIndicator(currentPlayer)

	// Update pot info
	sl.drawPotInfo(handPot, sabaccPot, 0)

	// Update bottom status line with pot information
	sl.UpdateStatusLine(round, handPot, sabaccPot, deckSize)
}

func (sl *ScreenLayout) drawTurnIndicator(currentPlayer string) {
	// Position turn indicator in a safe area - above the human player name
	MoveCursor(25, 14)
	fmt.Print(strings.Repeat(" ", 40)) // Clear wider area
	MoveCursor(25, 14)
	if currentPlayer == "Human" || currentPlayer == "" {
		fmt.Printf("%s\x10 YOUR TURN \x11%s", YellowHi, Reset)
	} else {
		// Extract just the player name (before any space or status text)
		playerName := strings.Fields(currentPlayer)[0]
		fmt.Printf("%s\x10 %s'S TURN \x11%s", YellowHi, strings.ToUpper(playerName), Reset)
	}
}

func (sl *ScreenLayout) drawPotInfo(gamePot, sabaccPot, sidePot int) {
	// Use the new helper function with embedded positioning
	potInfo := createPotInfo(sl, gamePot, sabaccPot, sidePot)
	fmt.Print(potInfo)
}

// UpdateStatusLine updates the game info
func (sl *ScreenLayout) UpdateStatusLine(round, handPot, sabaccPot, deckSize int) {
	// Use the new helper function that embeds positioning in the string
	statusBar := createStatusBar(sl, round, deckSize)
	fmt.Print(statusBar)
}

// UpdatePlayerInfo updates a player's name, credits, and total for new layout
func (sl *ScreenLayout) UpdatePlayerInfo(playerIndex int, name string, credits, total int, showTotal bool) {
	switch playerIndex {
	case 0: // Human player (bottom center)
		MoveCursor(sl.HumanPlayerX, sl.HumanNameY)
		fmt.Print(EraseLine)
		if showTotal {
			fmt.Printf("%s%s%s - Total: %s Credits: %d",
				GreenHi, name, Reset, displayHandValue(total), credits)
		} else {
			fmt.Printf("%s%s%s - Credits: %d", GreenHi, name, Reset, credits)
		}
	case 1, 2, 3, 4: // AI players (corners) - update name and credits on same line
		var x, y int
		var isLeft bool
		switch playerIndex {
		case 1: // Top-left (PHOOJA)
			x, y = sl.AIPlayer1X+portraitWidth+1, sl.AIPlayer1Y
			isLeft = true
		case 2: // Top-right (ASH-TAAC)  
			x, y = sl.AIPlayer2X, sl.AIPlayer2Y
			isLeft = false
		case 3: // Bottom-left (OOLANGA)
			x, y = sl.AIPlayer3X+portraitWidth+1, sl.AIPlayer3Y
			isLeft = true
		case 4: // Bottom-right (KY'ALA)
			x, y = sl.AIPlayer4X, sl.AIPlayer4Y
			isLeft = false
		}
		
		if isLeft {
			// Left side players: name followed by credits
			// Calculate exact space needed: name + space + $ + digits
			creditsText := fmt.Sprintf("$%d", credits)
			totalLength := len(name) + 1 + len(creditsText)
			
			// Clear only the exact space needed
			MoveCursor(x, y)
			fmt.Print(strings.Repeat(" ", totalLength))
			MoveCursor(x, y)
			fmt.Printf("%s%s %s%s%s", CyanHi, name, Yellow, creditsText, Reset)
		} else {
			// Right side players: name followed by credits, left-aligned at fixed position
			textX := x - 16  // Fixed 16 columns to the left of portrait
			
			// Calculate exact space needed: name + space + $ + digits
			creditsText := fmt.Sprintf("$%d", credits)
			totalLength := len(name) + 1 + len(creditsText)
			
			// Clear only the exact space needed
			MoveCursor(textX, y)
			fmt.Print(strings.Repeat(" ", totalLength))
			MoveCursor(textX, y)
			fmt.Printf("%s%s %s%s%s", CyanHi, name, Yellow, creditsText, Reset)
		}
	}
}

// ClearPlayerArea clears a player's card display area
func (sl *ScreenLayout) ClearPlayerArea(playerIndex int) {
	switch playerIndex {
	case 0: // Human player (bottom center)
		for i := 0; i < sl.CardHeight+2; i++ { // Clear extra line for asterisks
			MoveCursor(sl.HumanPlayerX, sl.HumanPlayerY+i)
			fmt.Print(EraseLine)
		}
	case 1, 2, 3, 4: // AI players - clear card areas next to portraits under names
		var x, y int
		switch playerIndex {
		case 1: // AI 1 - Top-left, cards next to portrait under name
			x, y = sl.AIPlayer1X+portraitWidth+1, sl.AIPlayer1Y+1
		case 2: // AI 2 - Top-right, cards left of portrait under name  
			x, y = sl.AIPlayer2X-16, sl.AIPlayer2Y+1
		case 3: // AI 3 - Bottom-left, cards next to portrait under name
			x, y = sl.AIPlayer3X+portraitWidth+1, sl.AIPlayer3Y+1
		case 4: // AI 4 - Bottom-right, cards left of portrait under name
			x, y = sl.AIPlayer4X-16, sl.AIPlayer4Y+1
		}
		// Clear AI card area with proper width for card display (max 15 columns)
		MoveCursor(x, y)
		fmt.Print(strings.Repeat(" ", 15)) // Clear card display line
		MoveCursor(x, y+1) // Clear asterisk line
		fmt.Print(strings.Repeat(" ", 15))
		MoveCursor(x, y+2) // Clear static field values line
		fmt.Print(strings.Repeat(" ", 15))
	}
}

// ClearMenuArea clears the menu/command area
func (sl *ScreenLayout) ClearMenuArea() {
	for i := 0; i < 3; i++ { // Menu area is 3 lines
		MoveCursor(1, sl.MenuY+i)
		fmt.Print(EraseLine)
		fmt.Print(VERTICAL_LINE + strings.Repeat(" ", sl.TerminalW-2) + VERTICAL_LINE)
	}
}

// ShowMenu displays the command menu
func (sl *ScreenLayout) ShowMenu(title string, options []MenuOption, prompt string) {
	sl.ClearMenuArea()

	// Show title
	MoveCursor(4, sl.MenuY)
	fmt.Printf("%s%s%s", GreenHi, title, Reset)

	// Show options
	MoveCursor(4, sl.MenuY+1)
	optionTexts := make([]string, 0)
	for _, opt := range options {
		if opt.Enabled {
			text := fmt.Sprintf("[%s%c%s] %s", YellowHi, opt.Key, Yellow, opt.Description)
			optionTexts = append(optionTexts, text)
		}
	}
	fmt.Printf("%s%s%s", White, strings.Join(optionTexts, "  "), Reset)

	// Show prompt
	MoveCursor(4, sl.MenuY+2)
	fmt.Printf("%s%s%s", Green, prompt, Reset)
}

// ShowCompactMenu displays just the options on one line without title or prompt, centered
func (sl *ScreenLayout) ShowCompactMenu(options []MenuOption) {
	// Clear just the menu line
	MoveCursor(1, sl.MenuY)
	fmt.Print(EraseLine)
	
	// Build option texts with new colors
	optionTexts := make([]string, 0)
	for _, opt := range options {
		if opt.Enabled {
			// Dark Magenta brackets, Bright Blue keys, Bright Magenta text
			text := fmt.Sprintf("%s[%s%c%s%s] %s%s%s", Magenta, BlueHi, opt.Key, Reset, Magenta, MagentaHi, opt.Description, Reset)
			optionTexts = append(optionTexts, text)
		}
	}
	
	// Join options and calculate center position
	menuText := strings.Join(optionTexts, "  ")
	
	// Strip ANSI codes to get actual display length for centering
	displayLength := len(stripANSI(menuText))
	startX := (sl.TerminalW - displayLength) / 2
	if startX < 1 {
		startX = 1
	}
	
	// Show centered menu
	MoveCursor(startX, sl.MenuY)
	fmt.Print(menuText)
}

// ClearCompactMenu clears the compact menu line
func (sl *ScreenLayout) ClearCompactMenu() {
	MoveCursor(1, sl.MenuY)
	fmt.Print(EraseLine)
}


// LogMessage adds a message to the game log
func (sl *ScreenLayout) LogMessage(message, msgType string) {
	sl.GameLog.AddMessage(message, msgType)
	sl.RefreshGameLog()
}

// DisplayMessage shows a temporary message
func (sl *ScreenLayout) DisplayMessage(message, msgType string, duration int) {
	// Simple implementation - just add to log for now
	sl.LogMessage(message, msgType)
}

// RefreshGameLog redraws the game log area with blue background and wraps long text
func (sl *ScreenLayout) RefreshGameLog() {
	// Clear the log area with blue background
	for i := 0; i < sl.GameLogH; i++ {
		MoveCursor(sl.GameLogX, sl.GameLogY+i)
		fmt.Printf("\x1b[30;44m%s\x1b[0m", strings.Repeat(" ", sl.GameLogW))
	}

	// Get recent messages and wrap them
	messages := sl.GameLog.GetRecentMessages()
	wrappedLines := []string{}
	
	// Wrap each message to fit within the log width (23 characters for text)
	maxTextLen := 23
	for _, msg := range messages {
		cleanMsg := stripANSI(msg)
		if len(cleanMsg) <= maxTextLen {
			wrappedLines = append(wrappedLines, msg)
		} else {
			// Wrap the message into multiple lines
			wrapped := wrapText(msg, maxTextLen)
			wrappedLines = append(wrappedLines, wrapped...)
		}
	}
	
	// Display the most recent wrapped lines (from bottom up)
	linesToShow := sl.GameLogH
	startIndex := len(wrappedLines) - linesToShow
	if startIndex < 0 {
		startIndex = 0
	}
	
	for i := 0; i < linesToShow && startIndex+i < len(wrappedLines); i++ {
		line := wrappedLines[startIndex+i]
		MoveCursor(sl.GameLogX, sl.GameLogY+i)
		
		// Start with blue background for entire line
		fmt.Print("\x1b[30;44m")
		
		// Print message with padding
		fmt.Printf(" %s", line)
		
		// Calculate remaining space and fill with blue background
		msgLen := len(stripANSI(line))
		if msgLen < maxTextLen {
			remaining := maxTextLen - msgLen
			fmt.Printf("\x1b[30;44m%s", strings.Repeat(" ", remaining))
		}
		fmt.Print(" ") // Right padding
		
		fmt.Print("\x1b[0m") // Reset at end of line
	}
}

// RenderPlayerCards renders cards for a player
func (sl *ScreenLayout) RenderPlayerCards(playerIndex int, cards []Card, staticField []Card, faceDown bool, renderer *CardRenderer, round, deckSize, handPot, sabaccPot int) {
	var x, y int

	switch playerIndex {
	case 0: // Human player
		x, y = sl.HumanPlayerX, sl.HumanPlayerY
	case 1: // AI 1 - Top-left, cards next to portrait under name
		x, y = sl.AIPlayer1X+portraitWidth+1, sl.AIPlayer1Y+1
	case 2: // AI 2 - Top-right, cards left of portrait under name  
		x, y = sl.AIPlayer2X-16, sl.AIPlayer2Y+1
	case 3: // AI 3 - Bottom-left, cards next to portrait under name
		x, y = sl.AIPlayer3X+portraitWidth+1, sl.AIPlayer3Y+1
	case 4: // AI 4 - Bottom-right, cards left of portrait under name
		x, y = sl.AIPlayer4X-16, sl.AIPlayer4Y+1
	default:
		return
	}

	// Clear the card area first
	sl.ClearPlayerArea(playerIndex)
	
	// Redraw status bar and pot info after clearing human player area (since they get wiped out)
	if playerIndex == 0 {
		sl.UpdateStatusLine(round, 0, 0, deckSize) // Use 0 for pots since this is just for Round/Deck display
		sl.drawPotInfo(handPot, sabaccPot, 0) // Redraw pot info with actual values
	}

	// Render cards
	for i, card := range cards {
		// More robust check for static field cards
		isStatic := false
		for _, staticCard := range staticField {
			if card.Value == staticCard.Value && card.Suit == staticCard.Suit && card.Name == staticCard.Name {
				isStatic = true
				break
			}
		}


		if faceDown {
			// Show face-down AI cards as solid colored blocks to hide values from human player
			if playerIndex > 0 { // AI players
				suitColor := getSuitColorForAI(card)

				// Position each card with proper spacing (2 characters per card: block + space)
				cardX := x + (i * 2)
				MoveCursor(cardX, y)
				fmt.Printf("%s%s%s", suitColor, SOLID_BLOCK, Reset) // Use solid block to hide card value
				
				// Add yellow asterisk under static field cards for AI players
				if isStatic {
					MoveCursor(cardX, y+1)
					fmt.Printf("%s*%s", Yellow, Reset)
				}
			} else {
				// Human player face-down cards
				cardX := x + (i * 4) // Keep original spacing for human cards
				MoveCursor(cardX, y)
				fmt.Printf("%s%s%s%s", Yellow, SOLID_BLOCK, SOLID_BLOCK, Reset)
				
				// Add yellow asterisk under static field cards for human player
				if isStatic {
					MoveCursor(cardX+1, y+sl.CardHeight)
					fmt.Printf("%s*%s", Yellow, Reset)
				}
			}
		} else {
			// Show actual card for human player
			if renderer != nil && playerIndex == 0 {
				// Render card row by row with proper cursor positioning
				cardX := x + (i * 4) // Keep original spacing for human cards
				sl.renderCardAtPosition(cardX, y, card, renderer)
				if isStatic {
					MoveCursor(cardX+2, y+sl.CardHeight)
					fmt.Printf("%s*%s", Yellow, Reset)
				}
			} else {
				// Fallback text representation
				cardX := x + (i * 4)
				MoveCursor(cardX, y)
				fmt.Printf("[%s]", card.String())
				if isStatic {
					MoveCursor(cardX+1, y+1)
					fmt.Printf("%s*%s", Yellow, Reset)
				}
			}
		}
	}

	// Render AI static field card values with proper spacing and +/- indicators
	if playerIndex > 0 {
		for i, card := range staticField {
			cardX := x + (i * 2) // Match the 2-character spacing used for AI cards
			MoveCursor(cardX, y+2) // Position below the asterisk
			
			// Display value with +/- indicator
			if card.Value > 0 {
				fmt.Printf("%s+%d%s", Yellow, card.Value, Reset)
			} else if card.Value < 0 {
				fmt.Printf("%s%d%s", Yellow, card.Value, Reset) // Negative already has - sign
			} else {
				fmt.Printf("%s0%s", Yellow, Reset)
			}
		}
	}
}


// GameLog methods
func (gl *GameLog) AddMessage(message, msgType string) {
	// Add color coding based on message type
	coloredMsg := message
	switch msgType {
	case "error":
		coloredMsg = Red + message + Reset
	case "success":
		coloredMsg = Green + message + Reset
	case "warning":
		coloredMsg = Yellow + message + Reset
	case "important":
		coloredMsg = RedHi + message + Reset
	case "action":
		coloredMsg = Cyan + message + Reset
	case "info":
		coloredMsg = White + message + Reset
	}

	gl.Messages = append(gl.Messages, coloredMsg)

	// Keep only recent messages (circular buffer)
	if len(gl.Messages) > gl.MaxLines*3 {
		gl.Messages = gl.Messages[len(gl.Messages)-gl.MaxLines:]
	}
}

func (gl *GameLog) GetRecentMessages() []string {
	if len(gl.Messages) <= gl.MaxLines {
		return gl.Messages
	}
	return gl.Messages[len(gl.Messages)-gl.MaxLines:]
}

func (gl *GameLog) Clear() {
	gl.Messages = make([]string, 0)
}

// Helper functions for AI card rendering

// getSuitColorForAI returns the appropriate color for AI card blocks based on suit
func getSuitColorForAI(card Card) string {
	switch card.Suit {
	case "Sabers", "Flasks":
		return Green // Green foreground for Sabers and Flasks
	case "Coins", "Staves":
		return Yellow // Yellow foreground for Coins and Staves
	case "Arcana":
		return Red // Red foreground for Arcana cards
	default:
		return White // White foreground for unknown suits
	}
}


// renderCardAtPosition renders a card at a specific position using proper cursor positioning
func (sl *ScreenLayout) renderCardAtPosition(x, y int, card Card, renderer *CardRenderer) {
	// Get card data from the database
	cardID := card.String()
	data, _, height, err := renderer.Database.GetCardData(cardID)
	if err != nil {
		// Fallback to simple representation
		MoveCursor(x, y)
		fmt.Printf("[%s]", card.String())
		return
	}

	// Split ANSI data into lines and render each line
	lines := strings.Split(string(data), "\r\n")
	for i, line := range lines {
		if i >= height {
			break
		}
		MoveCursor(x, y+i)
		fmt.Print(line)
	}
}

// wrapText wraps a message to fit within the specified width, preserving ANSI color codes
func wrapText(text string, maxWidth int) []string {
	if len(stripANSI(text)) <= maxWidth {
		return []string{text}
	}
	
	var lines []string
	remaining := text
	currentColor := "" // Track the active color code
	
	for len(stripANSI(remaining)) > maxWidth {
		// Find the best break point within maxWidth characters
		breakPoint := maxWidth
		cleanText := stripANSI(remaining)
		
		// Look for a space to break on (word wrapping)
		for i := maxWidth - 1; i >= maxWidth/2; i-- {
			if i < len(cleanText) && cleanText[i] == ' ' {
				breakPoint = i
				break
			}
		}
		
		// Extract the line up to the break point, preserving ANSI codes
		line := extractTextWithANSI(remaining, breakPoint)
		
		// Extract the current color from this line
		currentColor = extractCurrentColor(line)
		
		lines = append(lines, line)
		
		// Remove the extracted portion from remaining text
		remaining = remaining[findANSIAwarePosition(remaining, breakPoint):]
		
		// Skip leading spaces in the next line
		for len(remaining) > 0 && remaining[0] == ' ' {
			remaining = remaining[1:]
		}
		
		// Prepend the current color to the continuation line if we have one
		if currentColor != "" && len(stripANSI(remaining)) > 0 {
			remaining = currentColor + remaining
		}
	}
	
	// Add any remaining text as the last line
	if len(stripANSI(remaining)) > 0 {
		// Ensure final line has proper color if needed
		if currentColor != "" && !strings.Contains(remaining, "\x1b[") {
			remaining = currentColor + remaining
		}
		lines = append(lines, remaining)
	}
	
	return lines
}

// extractTextWithANSI extracts text up to a certain character count while preserving ANSI codes
func extractTextWithANSI(text string, charCount int) string {
	if charCount <= 0 {
		return ""
	}
	
	var result strings.Builder
	visibleCount := 0
	i := 0
	
	for i < len(text) && visibleCount < charCount {
		if text[i] == '\x1b' && i+1 < len(text) && text[i+1] == '[' {
			// ANSI escape sequence - copy it entirely
			start := i
			i += 2
			for i < len(text) && text[i] != 'm' {
				i++
			}
			if i < len(text) {
				i++ // Include the 'm'
			}
			result.WriteString(text[start:i])
		} else {
			// Regular character
			result.WriteByte(text[i])
			visibleCount++
			i++
		}
	}
	
	return result.String()
}

// extractCurrentColor extracts the last color code from a text string
func extractCurrentColor(text string) string {
	lastColorStart := -1
	i := 0
	
	for i < len(text)-1 {
		if text[i] == '\x1b' && text[i+1] == '[' {
			lastColorStart = i
		}
		i++
	}
	
	if lastColorStart == -1 {
		return ""
	}
	
	// Extract from lastColorStart to the 'm' character
	for i := lastColorStart + 2; i < len(text); i++ {
		if text[i] == 'm' {
			return text[lastColorStart : i+1]
		}
	}
	
	return ""
}

// findANSIAwarePosition finds the byte position after skipping a certain number of visible characters
func findANSIAwarePosition(text string, charCount int) int {
	if charCount <= 0 {
		return 0
	}
	
	visibleCount := 0
	i := 0
	
	for i < len(text) && visibleCount < charCount {
		if text[i] == '\x1b' && i+1 < len(text) && text[i+1] == '[' {
			// Skip ANSI escape sequence
			i += 2
			for i < len(text) && text[i] != 'm' {
				i++
			}
			if i < len(text) {
				i++ // Skip the 'm'
			}
		} else {
			// Regular character
			visibleCount++
			i++
		}
	}
	
	return i
}
